version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Chicago
    open-pull-requests-limit: 6
    target-branch: main
    versioning-strategy: increase-if-necessary
    groups:
      production-dependencies:
        dependency-type: production
      development-dependencies:
        dependency-type: development
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:30"
      timezone: America/Chicago
    open-pull-requests-limit: 4
    target-branch: main
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - dependencies
      - github-actions
